#!/usr/bin/env bash
# Pre-`up` secret bootstrap for the self-hosted team deployment.
#
# Neo4j's own official image reads NEO4J_AUTH as a plain environment
# variable at container boot, and Docker Compose resolves `.env`
# interpolation before any container's entrypoint runs. That means no
# in-container logic (e.g. memex-server's own entrypoint) can generate
# Neo4j's password after the fact — it must exist in docker/.env before
# `docker compose up` is invoked at all. See 06-RESEARCH.md Pattern 2 /
# Pitfall 2 for the full mechanical explanation of why this is a
# separate script from the memex-server entrypoint's own admin-key
# provisioning (docker/entrypoint-server.sh).
#
# Usage: ./docker/bootstrap-team-env.sh   (run once, before `docker compose up`)
set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"

if [ ! -f "$ENV_FILE" ]; then
  # Reuse the exact same primitive memex/watcher/registry.py's add_key()
  # already uses for bearer-key generation (secrets.token_hex()) rather
  # than hand-rolling randomness.
  NEO4J_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_hex(24))')"

  cat > "$ENV_FILE" <<EOF
# Generated by docker/bootstrap-team-env.sh — do not commit this file.
NEO4J_USER=neo4j
NEO4J_PASSWORD=${NEO4J_PASSWORD}
# Fill in your Gemini API key before running `docker compose up`.
GEMINI_API_KEY=
EOF

  # Holds a live secret on disk — restrict to owner read/write immediately
  # after writing, before printing any confirmation message.
  chmod 600 "$ENV_FILE"

  echo "Generated docker/.env with a new random Neo4j password."
  echo "Edit GEMINI_API_KEY in docker/.env before running 'docker compose up'."
else
  echo ".env already exists -- leaving it untouched (idempotent)."
fi
